-- 1. MASTERS (Профили мастеров)
CREATE TABLE IF NOT EXISTS masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    salon_name TEXT,
    phone TEXT,
    address TEXT,
    description TEXT,
    avatar_url TEXT,
    timezone TEXT DEFAULT 'Asia/Almaty', -- Добавили часовой пояс
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SERVICES (Услуги)
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    duration_min INTEGER DEFAULT 60,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. WORKING_HOURS (График работы)
CREATE TABLE IF NOT EXISTS working_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    slot_minutes INTEGER DEFAULT 60,
    UNIQUE(master_telegram_id, day_of_week)
);

-- 4. APPOINTMENTS (Записи)
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    client_telegram_id BIGINT NOT NULL,
    service_id BIGINT REFERENCES services(id),
    starts_at TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),

    client_phone TEXT NOT NULL,
    pet_name TEXT NOT NULL,
    pet_breed TEXT,
    pet_weight_kg NUMERIC,
    comment TEXT,
    idempotency_key TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Индекс от овербукинга
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_slot
ON appointments (master_telegram_id, starts_at)
WHERE status != 'cancelled';