-- 1. MASTERS (Профили мастеров)
CREATE TABLE IF NOT EXISTS masters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT NOT NULL UNIQUE,
    salon_name TEXT,
    phone TEXT,
    address TEXT,
    description TEXT,
    avatar_url TEXT,
    timezone TEXT DEFAULT 'Asia/Almaty',

    -- [NEW] Для разделения версий (Basic / Pro)
    is_premium BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. SERVICES (Услуги)
CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    duration_min INTEGER DEFAULT 60,
    is_active BOOLEAN DEFAULT TRUE,

    -- [NEW] Для иконок (dog/cat) и подробного описания
    category TEXT DEFAULT 'dog', -- 'dog' или 'cat'
    description TEXT,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. WORKING_HOURS (График работы)
CREATE TABLE IF NOT EXISTS working_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    slot_minutes INTEGER DEFAULT 60,
    UNIQUE(master_telegram_id, day_of_week)
);

-- 4. APPOINTMENTS (Записи)
CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_telegram_id BIGINT NOT NULL REFERENCES masters(telegram_id) ON DELETE CASCADE,
    client_telegram_id BIGINT NOT NULL,
    service_id BIGINT REFERENCES services(id),
    starts_at TIMESTAMPTZ NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'cancelled', 'completed')),

    -- Данные клиента
    client_phone TEXT NOT NULL,

    -- [NEW] Добавили имя и юзернейм клиента (нужны для уведомлений и карточек)
    client_name TEXT,
    client_username TEXT,

    -- Данные питомца
    pet_name TEXT NOT NULL,
    pet_breed TEXT,
    pet_weight_kg NUMERIC,
    comment TEXT,
    idempotency_key TEXT,

    -- [NEW] Флаги для авто-напоминаний (чтобы не слать дважды)
    reminder_5h_sent BOOLEAN DEFAULT FALSE,
    reminder_1h_sent BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Индекс от дублей (защита от двойного клика на одно время)
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_slot
ON appointments (master_telegram_id, starts_at)
WHERE status != 'cancelled';